"""Add profile_image to users table

Revision ID: 337674563d57
Revises: 
Create Date: 2025-09-28 10:01:07.831240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337674563d57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
